// <auto-generated />
using System;
using DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbContext.Migrations.mysqlDbContext
{
    [DbContext(typeof(MainDbContext.MySqlDbContext))]
    partial class MySqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DbModels.AddressDbM", b =>
                {
                    b.Property<Guid>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Seeded")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int>("ZipCode")
                        .HasColumnType("int");

                    b.HasKey("AddressId");

                    b.HasIndex("StreetAddress", "ZipCode", "City", "Country")
                        .IsUnique();

                    b.ToTable("Addresses", "supusr");
                });

            modelBuilder.Entity("DbModels.FriendDbM", b =>
                {
                    b.Property<Guid>("FriendId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Seeded")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("FriendId");

                    b.HasIndex("AddressId");

                    b.HasIndex("FirstName", "LastName");

                    b.HasIndex("LastName", "FirstName");

                    b.ToTable("Friends", "supusr");
                });

            modelBuilder.Entity("DbModels.PetDbM", b =>
                {
                    b.Property<Guid>("PetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("FriendId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<int>("Mood")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Seeded")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("strKind")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("strMood")
                        .HasColumnType("varchar(200)");

                    b.HasKey("PetId");

                    b.HasIndex("FriendId");

                    b.ToTable("Pets", "supusr");
                });

            modelBuilder.Entity("DbModels.QuoteDbM", b =>
                {
                    b.Property<Guid>("QuoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Author")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("QuoteText")
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Seeded")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("QuoteId");

                    b.ToTable("Quotes", "supusr");
                });

            modelBuilder.Entity("FriendDbMQuoteDbM", b =>
                {
                    b.Property<Guid>("FriendsDbMFriendId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("QuotesDbMQuoteId")
                        .HasColumnType("char(36)");

                    b.HasKey("FriendsDbMFriendId", "QuotesDbMQuoteId");

                    b.HasIndex("QuotesDbMQuoteId");

                    b.ToTable("FriendDbMQuoteDbM", "supusr");
                });

            modelBuilder.Entity("DbModels.FriendDbM", b =>
                {
                    b.HasOne("DbModels.AddressDbM", "AddressDbM")
                        .WithMany("FriendsDbM")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AddressDbM");
                });

            modelBuilder.Entity("DbModels.PetDbM", b =>
                {
                    b.HasOne("DbModels.FriendDbM", "FriendDbM")
                        .WithMany("PetsDbM")
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FriendDbM");
                });

            modelBuilder.Entity("FriendDbMQuoteDbM", b =>
                {
                    b.HasOne("DbModels.FriendDbM", null)
                        .WithMany()
                        .HasForeignKey("FriendsDbMFriendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbModels.QuoteDbM", null)
                        .WithMany()
                        .HasForeignKey("QuotesDbMQuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DbModels.AddressDbM", b =>
                {
                    b.Navigation("FriendsDbM");
                });

            modelBuilder.Entity("DbModels.FriendDbM", b =>
                {
                    b.Navigation("PetsDbM");
                });
#pragma warning restore 612, 618
        }
    }
}
